import {
	User,
	Calendar,
	DollarSign,
	Percent,
	Building,
	Package,
	Zap,
	FileText,
	Clock,
	ShoppingBag,
	Box,
	Users,
	BarChart2,
	Home,
	ShoppingCart,
	Layers,
} from "lucide-react"
import { NavItem } from "@/types/nav.interface"
import { UserRole } from "@/types/enums"

export const navItems: NavItem[] = [
	{
		id: "monitoring",
		name: "monitoring",
		title: "Monitoring",
		translationKey: "nav.monitoring",
		children: [
			{ id: "home", name: "home", title: "Home", translationKey: "nav.home", icon: Home, href: "/" },
			{ id: "orders", name: "orders", title: "Orders", translationKey: "nav.orders", icon: ShoppingCart, href: "/orders" },
			{ id: "products", name: "products", title: "Products", translationKey: "nav.products", icon: Package, href: "/products" },
			{ id: "collections", name: "collections", title: "Collections", translationKey: "nav.collections", icon: Layers, href: "/collections" },
			{ id: "customers", name: "customers", title: "Customers", translationKey: "nav.customers", icon: Users, href: "/customers" },
		],
	},
	{
		id: "employee",
		name: "employee",
		title: "Employee",
		translationKey: "nav.employee",
		children: [
			{ id: "employee", name: "employee", title: "Employee", translationKey: "nav.employee", icon: User, href: "/employee" },
			{ id: "attendance", name: "attendance", title: "Attendance", translationKey: "nav.attendance", icon: Calendar, href: "/attendance" },
			{ id: "payroll", name: "payroll", title: "Payroll", translationKey: "nav.payroll", icon: DollarSign, href: "/payroll" },
		],
	},
	{
		id: "marketing",
		name: "marketing",
		title: "Marketing",
		translationKey: "nav.marketing",
		children: [{ id: "discounts", name: "discounts", title: "Discounts", translationKey: "nav.discounts", icon: Percent, href: "/discounts" }],
	},
	{
		id: "warehouses",
		name: "warehouses",
		title: "Warehouses",
		translationKey: "nav.warehouses",
		children: [
			{ id: "warehouse", name: "warehouse", title: "Warehouse", translationKey: "nav.warehouse", icon: Building, href: "/warehouse" },
			{ id: "stock_in", name: "stock_in", title: "Stock-in", translationKey: "nav.stockIn", icon: Package, href: "/stock-in" },
			{ id: "stock_out", name: "stock_out", title: "Stock-out", translationKey: "nav.stockOut", icon: Package, href: "/stock-out" },
			{ id: "produce", name: "produce", title: "Production", translationKey: "nav.produce", icon: Zap, href: "/produce" },
		],
	},
	{
		id: "utilities",
		name: "utilities",
		title: "Utilities",
		translationKey: "nav.utilities",
		children: [
			{ id: "utility", name: "utility", title: "Utility", translationKey: "nav.utility", icon: Zap, href: "/utility" },
			{ id: "invoice", name: "invoice", title: "Invoice", translationKey: "nav.invoice", icon: FileText, href: "/invoice" },
		],
	},
	{
		id: "reports",
		name: "reports",
		title: "Reports",
		translationKey: "nav.reports",
		children: [
			{ id: "reports_daily", name: "reports_daily", title: "Daily report", translationKey: "nav.dailyReport", icon: Clock, href: "/reports/daily" },
			{ id: "reports_employee", name: "reports_employee", title: "Employee report", translationKey: "nav.employeeReport", icon: User, href: "/reports/employee" },
			{ id: "reports_order", name: "reports_order", title: "Order report", translationKey: "nav.orderReport", icon: ShoppingBag, href: "/reports/order" },
			{ id: "reports_stock", name: "reports_stock", title: "Stock report", translationKey: "nav.stockReport", icon: Box, href: "/reports/stock" },
			{ id: "reports_customer", name: "reports_customer", title: "Customer report", translationKey: "nav.customerReport", icon: Users, href: "/reports/customer" },
			{
				id: "reports_activity", name: "reports_activity", title: "Operating Report",
				translationKey: "nav.operatingReport",
				icon: BarChart2,
				href: "/reports/activity",
			},
			{ id: "reports_utility", name: "reports_utility", title: "Utility Report", translationKey: "nav.utilityReport", icon: Zap, href: "/reports/utility" },
		],
	},
]

export const ROLE_LABELS = {
  [UserRole.super_admin]: "Super Admin",
  [UserRole.admin]: "Admin",
  [UserRole.manager]: "Manager",
  [UserRole.staff]: "Staff",
  [UserRole.customer]: "Customer",
} as const

// Default page access by role
export const DEFAULT_ROLE_PERMISSIONS: Record<UserRole, string[]> = {
  super_admin: navItems.flatMap((cat) => cat.children?.map((page) => page.id || "") || []),
  admin: [
    "home",
    "orders",
    "products",
    "collections",
    "customers",
    "employee",
    "attendance",
    "payroll",
    "discounts",
    "warehouse",
    "stock_in",
    "stock_out",
    "produce",
    "utility",
    "invoice",
    "reports_daily",
    "reports_employee",
    "reports_order",
    "reports_stock",
    "reports_customer",
    "reports_activity",
    "reports_utility",
  ],
  manager: [
    "home",
    "orders",
    "products",
    "collections",
    "customers",
    "attendance",
    "warehouse",
    "stock_in",
    "stock_out",
    "produce",
    "reports_daily",
    "reports_stock",
    "reports_activity",
  ],
  staff: ["home", "orders", "products", "collections", "attendance", "warehouse", "stock_in", "stock_out"],
  customer: ["home", "orders"],
}